# Generated by Django 4.2.28 on 2026-02-17 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_applicantprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('password_reset', 'パスワードリセット'), ('shelter_registration', '団体登録通知'), ('shelter_approval', '団体承認通知'), ('shelter_rejection', '団体否認通知'), ('application_status', '応募ステータス変更'), ('other', 'その他')], max_length=50, verbose_name='メール種別')),
                ('to_email', models.EmailField(max_length=254, verbose_name='送信先')),
                ('from_email', models.EmailField(default='noreply@example.com', max_length=254, verbose_name='送信元')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('body', models.TextField(verbose_name='本文')),
                ('status', models.CharField(choices=[('pending', '送信待ち'), ('sent', '送信済み'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='送信状態')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信日時')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='リトライ回数')),
                ('max_retries', models.PositiveSmallIntegerField(default=3, verbose_name='最大リトライ回数')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='関連ユーザー')),
            ],
            options={
                'verbose_name': 'メール送信ログ',
                'verbose_name_plural': 'メール送信ログ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='accounts_em_status_2bc223_idx'), models.Index(fields=['email_type'], name='accounts_em_email_t_7475ad_idx'), models.Index(fields=['to_email'], name='accounts_em_to_emai_96907b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='モデル名')),
                ('object_id', models.PositiveIntegerField(verbose_name='オブジェクトID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='オブジェクト表現')),
                ('action', models.CharField(choices=[('create', '作成'), ('update', '更新'), ('delete', '削除')], max_length=20, verbose_name='操作')),
                ('changes', models.JSONField(default=dict, verbose_name='変更内容')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
            ],
            options={
                'verbose_name': '監査ログ',
                'verbose_name_plural': '監査ログ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='accounts_au_model_n_76c60d_idx'), models.Index(fields=['actor'], name='accounts_au_actor_i_4b63b5_idx'), models.Index(fields=['created_at'], name='accounts_au_created_606b86_idx'), models.Index(fields=['action'], name='accounts_au_action_5ca9a9_idx')],
            },
        ),
    ]
