# Generated by Django 4.2.28 on 2026-02-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_emaillog_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='housing_type',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='moving_plan',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='pet_allowed',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='income_status',
            field=models.CharField(blank=True, choices=[('stable', '安定している'), ('unstable', '不安定')], max_length=20, null=True, verbose_name='収入状況'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', '既婚者'), ('single', '単身者')], max_length=20, null=True, verbose_name='既婚者か単身者の記入'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='pet_policy_confirmed',
            field=models.BooleanField(default=False, verbose_name='住居のペット可否について確認済み'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='residence_area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='居住エリア（都道府県）'),
        ),
    ]
