# Generated by Django 4.2.28 on 2026-02-24 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_applicantprofile_housing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='二段階認証'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('password_reset', 'パスワードリセット'), ('shelter_registration', '団体登録通知'), ('shelter_approval', '団体承認通知'), ('shelter_rejection', '団体否認通知'), ('application_status', '応募ステータス変更'), ('two_factor', '二段階認証コード'), ('other', 'その他')], max_length=50, verbose_name='メール種別'),
        ),
        migrations.CreateModel(
            name='TwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='コード')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_codes', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '二段階認証コード',
                'verbose_name_plural': '二段階認証コード',
                'ordering': ['-created_at'],
            },
        ),
    ]
