# Generated by Django 4.2.28 on 2026-02-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0006_shelter_review_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='shelters/headers/', verbose_name='ヘッダー画像'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='shelters/logos/', verbose_name='団体ロゴアイコン'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='public_profile_enabled',
            field=models.BooleanField(default=False, help_text='承認済みの団体のみ公開可能です', verbose_name='プロフィール一般公開'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='rescue_accepting',
            field=models.BooleanField(default=False, verbose_name='一般からの保護受付'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='rescue_area_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='保護受付地域'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='rescue_notes',
            field=models.TextField(blank=True, verbose_name='保護受付に関する注意事項'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='support_donation_url',
            field=models.URLField(blank=True, verbose_name='寄付・支援金リンク'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='support_goods_url',
            field=models.URLField(blank=True, verbose_name='物資支援リンク'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='support_message',
            field=models.TextField(blank=True, verbose_name='支援のお願いメッセージ'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='business_hours',
            field=models.TextField(blank=True, verbose_name='営業日・営業時間・定休日'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='description',
            field=models.TextField(blank=True, help_text='活動方針、譲渡の流れ、カフェの雰囲気など', verbose_name='団体紹介文'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='review_message',
            field=models.TextField(blank=True, verbose_name='審査メッセージ'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='transfer_available_hours',
            field=models.TextField(blank=True, verbose_name='譲渡対応可能な時間帯'),
        ),
        migrations.AlterField(
            model_name='shelteruser',
            name='role',
            field=models.CharField(choices=[('admin', '管理者'), ('staff', 'スタッフ')], default='staff', max_length=20, verbose_name='役割'),
        ),
    ]
