# Generated by Django 4.2.28 on 2026-02-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0009_cat_is_public_alter_cat_estimated_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='human_distance',
        ),
        migrations.AddField(
            model_name='cat',
            name='affection_level',
            field=models.PositiveSmallIntegerField(choices=[(5, 'とろとろ甘えん坊（膝乗り・抱っこ大好き）'), (4, '甘えん坊（ナデナデ大好き）'), (3, 'ツンデレ・気まぐれ（気が向くと甘える）'), (2, 'クール・マイペース（適度な距離感）'), (1, '怖がり・修行中（ゆっくり仲良くなろう）')], default=3, verbose_name='甘えん坊度'),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_elderly_ok',
            field=models.BooleanField(default=False, verbose_name='高齢者応募可'),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_single_ok',
            field=models.BooleanField(default=False, verbose_name='単身者応募可'),
        ),
        migrations.AddField(
            model_name='cat',
            name='maintenance_level',
            field=models.CharField(choices=[('easy', '初心者でも安心（協力的）'), ('normal', '少しコツが必要（普通）'), ('hard', '経験者向き（要練習）')], default='normal', help_text='爪切り・投薬・ブラッシングなどのしやすさ', max_length=20, verbose_name='お手入れ難易度'),
        ),
        migrations.AddField(
            model_name='cat',
            name='other_terms',
            field=models.TextField(blank=True, help_text='例: ペット可物件必須、脱走防止対策必須など', verbose_name='その他譲渡条件'),
        ),
    ]
