# Generated by Django 4.2.28 on 2026-02-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0010_remove_cat_human_distance_cat_affection_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='is_elderly_ok',
            field=models.BooleanField(default=False, verbose_name='高齢者応募可（非推奨）'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='is_single_ok',
            field=models.BooleanField(default=False, verbose_name='単身者応募可（非推奨）'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='other_terms',
            field=models.TextField(blank=True, help_text='例：ペット可物件必須、脱走防止対策必須、単身者・高齢者の応募可否など。詳細な条件を記載することで、ミスマッチを減らせます。', verbose_name='譲渡条件'),
        ),
    ]
