# Generated by Django 4.2.28 on 2026-02-11 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0009_cat_is_public_alter_cat_estimated_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='お気に入り登録日時')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='cats.cat', verbose_name='猫')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'お気に入り',
                'verbose_name_plural': 'お気に入り',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='favorites_f_user_id_645357_idx'), models.Index(fields=['cat'], name='favorites_f_cat_id_e630cd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'cat'), name='unique_user_cat_favorite'),
        ),
    ]
